name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test hello World
      id: test-hello-world
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test hello World
        setup-command: ''
        command: run
        input: |-
          #include <stdio.h>

          int main() {
              printf("Hello, World!\n");
              return 0;
          }
        expected-output: Hello World
        comparison-method: contains
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-HELLO-WORLD_RESULTS: "${{steps.test-hello-world.outputs.result}}"
      with:
        runners: test-hello-world
